<h2>CS 3780/5780 Creative Project: </h2>
<h3>Emotion Classification of Natural Language</h3>

Names and NetIDs for your group members:

-   Dihong Luo (dl2247)
-   Tristan Feng (rf468)
-   Zhihan Chen (zc523)

<h3>Introduction:</h3>

<p> The creative project is about conducting a real-world machine learning project on your own, with everything that is involved. Unlike in the programming projects 1-5, where we gave you all the scaffolding and you just filled in the blanks, you now start from scratch. The past programming projects provide templates for how to do this (and you can reuse part of your code if you wish), and the lectures provide some of the methods you can use. So, this creative project brings realism to how you will use machine learning in the real world.  </p>

The task you will work on is classifying texts to human emotions. Through words, humans express feelings, articulate thoughts, and communicate our deepest needs and desires. Language helps us interpret the nuances of joy, sadness, anger, and love, allowing us to connect with others on a deeper level. Are you able to train an ML model that recognizes the human emotions expressed in a piece of text? <b>Please read the project description PDF file carefully and follow the instructions there. Also make sure you write your code and answers to all the questions in this Jupyter Notebook </b> </p>

<p>

<h2>Part 0: Basics</h2><p>

<h3>0.1 Import:</h3><p>
Please import necessary packages to use. Note that learning and using packages are recommended but not required for this project. Some official tutorial for suggested packacges includes:
    
https://scikit-learn.org/stable/tutorial/basic/tutorial.html
    
https://pytorch.org/tutorials/
    
https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html
<p>

In [ ]:
import re
from typing import Literal

import numpy as np
import pandas as pd
import torch
import transformers
from sklearn import model_selection, naive_bayes, svm
from sklearn.feature_extraction import text as sklearn_text

<h3>0.2 Accuracy and Mean Squared Error:</h3><p>
To measure your performance in the Kaggle Competition, we are using accuracy. As a recap, accuracy is the percent of labels you predict correctly. To measure this, you can use library functions from sklearn. A simple example is shown below. 
<p>

In [ ]:
from sklearn.metrics import accuracy_score

y_pred = [3, 2, 1, 0, 1, 2, 3]
y_true = [0, 1, 2, 3, 1, 2, 3]
accuracy_score(y_true, y_pred)

0.42857142857142855

<h2>Part 1: Basic</h2><p>
Note that your code should be commented well and in part 1.4 you can refer to your comments.

<h3>1.1 Load and preprocess the dataset:</h3><p>
We provide how to load the data on Kaggle's Notebook.
<p>

In [ ]:
train = pd.read_csv("/kaggle/input/cs-3780-5780-how-do-you-feel/train.csv")
train_text = train["text"]
train_label = train["label"]

test = pd.read_csv("/kaggle/input/cs-3780-5780-how-do-you-feel/train.csv")
test_id = test["id"]
test_text = test["text"]

In [ ]:
train

                                                   text  label
0     i interact with on a daily basis either in rea...      1
1     Stranger than fiction. Can't even begin to com...      1
2     i sit here with the aftermath feeling so damn ...      1
3                           Great job! Hats off to you.     25
4     i hate you threads posted by people just whini...      9
...                                                 ...    ...
9995                                  im feeling so shy      4
9996  Honestly if they were so worried about the tub...     20
9997  Don't wear out our [NAME]. We need him if this...     10
9998                                    Happy new year!     19
9999                           I got 4 wheel drive bro!     12

[10000 rows x 2 columns]

In [ ]:
test

          id                                               text
0          0             im feeling like a hot potato right now
1          1  i feel that are becoming impressed upon my lit...
2          2  id ever held any girls hand but boy did i sure...
3          3  i feel thats when i feel my grief over the bra...
4          4  i feel will never been resolved in a way to ke...
...      ...                                                ...
14995  14995  i feel greedy in that im looking forward to th...
14996  14996                                 i was feeling cold
14997  14997  Yeah deffo seen mom do that trick with a Hotdo...
14998  14998                       i go to bed feeling defeated
14999  14999  i have gained more confidence within myself as...

[15000 rows x 2 columns]

In [ ]:
def preprocess(text: str) -> str:
    # Convert the text to lowercase
    text = text.lower()

    # Remove all non-alphabetical characters except spaces
    text = re.sub(r'[^a-z\s]', '', text)

    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [ ]:
def build_vectorizer(
    train_text: np.ndarray,
    method: Literal['bow', 'tfidf'],
    min_df: float = 1,
    max_df: float = 1,
    max_features: int | None = None,
) -> sklearn_text.CountVectorizer | sklearn_text.TfidfVectorizer:
    if method == 'bow':  # Bag-of-Words vectorizer
        vectorizer = sklearn_text.CountVectorizer(
            lowercase=True,
            stop_words='english',
            max_features=max_features,
        )
    elif method == 'tfidf':  # TF-IDF vectorizer
        vectorizer = sklearn_text.TfidfVectorizer(
            lowercase=True,
            stop_words='english',
            min_df=min_df,
            max_df=max_df,
            max_features=max_features,
        )
    else:
        raise ValueError(f'Unsupported method: {method}')

    # Fit the vectorizer to the training text data
    vectorizer.fit(train_text)

    return vectorizer

<h3>1.2 Use At Least Two Training Algorithms from class:</h3><p>
You need to use at least two training algorithms from class. You can use your code from previous projects or any packages you imported in part 0.1.

In [ ]:
# Linear SVM
def train_svm(
    X_train: np.ndarray,
    X_test: np.ndarray,
    y_train: np.ndarray,
    y_test: np.ndarray | None = None,
    C: float = 1,
    max_iter: int = 1000,
    random_state: int | None = 42,
) -> tuple[np.ndarray, float | None]:
    # Initialize the Linear SVM model with specified parameters
    svm_model = svm.LinearSVC(C=C, max_iter=max_iter, random_state=random_state)

    # Train the model on the training data
    svm_model.fit(X_train, y_train)

    # Predict labels for the test data
    y_pred = svm_model.predict(X_test)

    # Compute accuracy if test labels are provided
    if y_test is not None:
        accuracy = float(accuracy_score(y_test, y_pred))
    else:
        accuracy = None

    return y_pred, accuracy


# Naive Bayes
def train_nb(
    X_train: np.ndarray,
    X_test: np.ndarray,
    y_train: np.ndarray,
    y_test: np.ndarray | None = None,
    alpha: float = 1,
) -> tuple[np.ndarray, float | None]:
    # Initialize the Naive Bayes model with the specified smoothing parameter
    nb_model = naive_bayes.MultinomialNB(alpha=alpha)

    # Train the Naive Bayes model on the training data
    nb_model.fit(X_train, y_train)

    # Predict labels for the test data
    y_pred = nb_model.predict(X_test)

    # Compute accuracy if test labels are provided
    if y_test is not None:
        accuracy = float(accuracy_score(y_test, y_pred))
    else:
        accuracy = None

    return y_pred, accuracy

<h3>1.3 Training, Validation and Model Selection:</h3><p>
You need to split your data to a training set and validation set or performing a cross-validation for model selection.

In [ ]:
def kfold_validation(
    train_text: np.ndarray,
    train_label: np.ndarray,
    params: dict,
    method: Literal['bow', 'tfidf'],
    model: Literal['svm', 'nb'],
    k: int = 5,
    min_df: float = 1,
    max_df: float = 1,
    max_features: int | None = None,
) -> float:
    # Initialize k-fold cross-validation splitter with k splits
    kfold = model_selection.KFold(n_splits=k, shuffle=True, random_state=42)
    scores = []

    for train_idx, val_idx in kfold.split(train_text, train_label):
        # Split the data into training and validation sets for the current fold
        X_train, X_val = train_text[train_idx], train_text[val_idx]
        y_train, y_val = train_label[train_idx], train_label[val_idx]

        # Build a vectorizer (Bag-of-Words or TF-IDF) and fit it to the training data
        vectorizer = build_vectorizer(X_train, method, min_df, max_df, max_features)

        # Transform training and validation data into feature vectors
        X_train = vectorizer.transform(X_train).toarray()  # pyright: ignore
        X_val = vectorizer.transform(X_val).toarray()  # pyright: ignore

        # Train the specified model and evaluate it on the validation set
        if model == 'svm':
            _, val_accuracy = train_svm(
                X_train,
                X_val,
                y_train,
                y_val,
                C=params['C'],
                max_iter=params['max_iter'],
            )
        elif model == 'nb':
            _, val_accuracy = train_nb(
                X_train,
                X_val,
                y_train,
                y_val,
                alpha=params['alpha'],
            )
        else:
            # Raise an error if an unsupported model type is specified
            raise ValueError(f'Unsupported model type: {model}')

        # Append the validation accuracy for the current fold to the scores list
        scores.append(val_accuracy)

    return float(np.mean(scores))

In [ ]:
def grid_search(
    train_text: np.ndarray,
    train_label: np.ndarray,
    param_grid: dict,
    method: Literal['bow', 'tfidf'],
    model: Literal['svm', 'nb'],
    k: int = 5,
    min_df: float = 1,
    max_df: float = 1,
    max_features: int | None = None,
) -> dict:
    best_score = -np.inf
    best_params = None

    # Iterate through all parameter combinations in the parameter grid
    for param_combination in model_selection.ParameterGrid(param_grid):
        val_score = kfold_validation(
            train_text,
            train_label,
            param_combination,
            method,
            model,
            k,
            min_df,
            max_df,
            max_features,
        )

        # Log the current parameter combination and its validation accuracy
        print(f'Params: {param_combination}, Validation Accuracy: {val_score}')

        # Update the best score and parameters if the current combination performs better
        if val_score > best_score:
            best_score = val_score
            best_params = param_combination

    return {'best_params': best_params, 'best_score': best_score}

In [ ]:
# Apply preprocessing to clean the training text data,
# and convert training data to a NumPy array
train_text_cleaned = np.array(train_text.apply(preprocess))
train_label = np.array(train_label)

In [ ]:
# Define the parameter grid for SVM
param_grid_svm = {'C': [0.001, 0.01, 0.1, 1], 'max_iter': [500, 1000]}

# Perform grid search to find the best hyperparameters for SVM
best_svm_result = grid_search(
    train_text_cleaned,
    train_label,
    param_grid=param_grid_svm,
    method='bow',  # Use Bag-of-Words as the feature extraction method
    model='svm',
    k=5,  # Perform 5-fold cross-validation
)

# Print the best parameters and validation accuracy found during grid search
print(f"Best SVM Parameters: {best_svm_result['best_params']}")
print(f"Best SVM Validation Accuracy: {best_svm_result['best_score']}")

Params: {'C': 0.001, 'max_iter': 500}, Validation Accuracy: 0.4338
Params: {'C': 0.001, 'max_iter': 1000}, Validation Accuracy: 0.4338
Params: {'C': 0.01, 'max_iter': 500}, Validation Accuracy: 0.6555
Params: {'C': 0.01, 'max_iter': 1000}, Validation Accuracy: 0.6555
Params: {'C': 0.1, 'max_iter': 500}, Validation Accuracy: 0.7258000000000001
Params: {'C': 0.1, 'max_iter': 1000}, Validation Accuracy: 0.7258000000000001
Params: {'C': 1, 'max_iter': 500}, Validation Accuracy: 0.7043
Params: {'C': 1, 'max_iter': 1000}, Validation Accuracy: 0.7043
Best SVM Parameters: {'C': 0.1, 'max_iter': 500}
Best SVM Validation Accuracy: 0.7258000000000001

In [ ]:
# Define the parameter grid for Naive Bayes
param_grid_nb = {'alpha': [0.01, 0.1, 0.5, 1.0, 2.0]}

# Perform grid search to find the best hyperparameters for Naive Bayes
best_nb_result = grid_search(
    train_text_cleaned,
    train_label,
    param_grid=param_grid_nb,
    method='bow',  # Use Bag-of-Words as the feature extraction method
    model='nb',
    k=5,  # Perform 5-fold cross-validation
)

# Print the best parameters and validation accuracy found during grid search
print(f"Best Naive Bayes Parameters: {best_nb_result['best_params']}")
print(f"Best Naive Bayes Accuracy: {best_nb_result['best_score']}")

Params: {'alpha': 0.01}, Validation Accuracy: 0.5406
Params: {'alpha': 0.1}, Validation Accuracy: 0.5841999999999999
Params: {'alpha': 0.5}, Validation Accuracy: 0.5776999999999999
Params: {'alpha': 1.0}, Validation Accuracy: 0.5394
Params: {'alpha': 2.0}, Validation Accuracy: 0.4936999999999999
Best Naive Bayes Parameters: {'alpha': 0.1}
Best Naive Bayes Accuracy: 0.5841999999999999

In [ ]:
# Preprocess the test text data
test_text_cleaned = np.array(test_text.apply(preprocess))

# Build a vectorizer using the training text data with Bag-of-Words (BoW) method
vectorizer = build_vectorizer(train_text_cleaned, 'bow')

# Transform the text data into numerical feature matrices
X_train = vectorizer.transform(train_text_cleaned).toarray()  # pyright: ignore
X_test = vectorizer.transform(test_text_cleaned).toarray()  # pyright: ignore

# Convert training labels to a NumPy array
y_train = np.array(train_label)

In [ ]:
# Train the SVM model using the best hyperparameters found during grid search
svm_prediction, _ = train_svm(
    X_train,
    X_test,
    y_train,
    C=best_svm_result['best_params']['C'],
    max_iter=best_svm_result['best_params']['max_iter'],
)

id = range(15000)
submission = pd.DataFrame({'id': id, 'label': svm_prediction})

# Save the submission file in the specified directory
submission.to_csv('/kaggle/working/submission_svm.csv', index=False)

In [ ]:
# Train the Naive Bayes model using the best hyperparameters found during grid search
nb_prediction, _ = train_nb(
    X_train,
    X_test,
    y_train,
    alpha=best_nb_result['best_params']['alpha'],
)

id = range(15000)
submission = pd.DataFrame({'id': id, 'label': nb_prediction})

# Save the submission file in the specified directory
submission.to_csv('/kaggle/working/submission_nb.csv', index=False)

<h3>1.4 Explanation in Words:</h3><p>
    You need to answer the following questions in the markdown cell after this cell:

1.4.1 How did you formulate the learning problem?

1.4.2 Which two learning methods from class did you choose and why did you made the choices?

1.4.3 How did you do the model selection?

1.4.4 Does the test performance reach the first baseline "Tiny Piney"? (Please include a screenshot of Kaggle Submission)

##### 1.4.1 How did you formulate the learning problem?

-   The objective is to map input text data to one of 28 predefined emotion classes. The raw text data was preprocessed to remove noise, including converting text to lowercase, removing non-alphabetical characters, and stripping extra spaces. Following this, we choose two types of data processing techniques: the Bag-of-Words (BoW) and TF-IDF vectorizer to transform the textual data into a numerical feature representation. After numerous tasts, we choose BoW for its suitabiity for different models. Then the learning task was designed as a supervised learning problem, where the model learns patterns from labeled training data (train.csv) and predicts labels for the test data (test.csv). The models were trained to minimize classification errors by optimizing their parameters on the training data. At the same time, the key objectives in formulating the learning problem are: Accurate Prediction, Computational Efficiency Interpretability and Generalization.

##### 1.4.2 Which two learning methods from class did you choose and why did you made the choices?

-   We chose Linear SVM and Naive Bayes from class. Firstly, we think Linear SVM is well-suited for high-dimensional text data like Bag-of-Words due to its efficiency and ability to create robust decision boundaries. It's also computationally manageable and scalable for the given dataset size.
    Plus,regularization through the C parameter allows us to balance complexity and performance and avoid overfitting. As for Naive Bayes, it assumes feature independence, which aligns well with Bag-of-Words representation. It can provide good baseline performance in text classification tasks.

-   We have also tried boosting method such as XGBoost and logic regression during experimentation but found to be too computationally expensive given the resource constraints on Kaggle.

##### 1.4.3 How did you do the model selection?

-   K-Fold Cross-Validation: The dataset was split into training and validation sets using 5-fold cross-validation, which ensured robust evaluation by testing the model's performance on multiple subsets of the data and reducing variance in the validation scores.

-   Grid Search: Hyperparameter tuning was performed by systematically testing combinations of parameters. For SVM, the parameters C and max_iter were tuned. For Naive Bayes, the smoothing parameter alpha was optimized. The grid search iterated over these combinations to identify the best-performing configuration based on cross-validation accuracy.

-   Prediction: The Grid Search returns the parameter which produces the best efficiency. We use this best parameter to train the model and use the trained model to predict the results.

##### 1.4.4 Does the test performance reach the first baseline "Tiny Piney"? (Please include a screenshot of Kaggle Submission)

-   Yes, it does.

<div style="text-align: center">
    <img
        alt="SVM Submission"
        src="https://github.com/Andy-Dihong-Luo/My-Image-Host/blob/master/Final%20Project/notebook_template/svm_submission_1733710593703.png?raw=true"
        width="90%"
    />
</div>

<h2>Part 2: Be creative!</h2><p>

<h3>2.1 Open-ended Code:</h3><p>
You may follow the steps in part 1 again but making innovative changes like using new training algorithms, etc. Make sure you explain everything clearly in part 2.2. Note that beating "Zero Hero" is only a small portion of this part. Any creative ideas will receive most points as long as they are reasonable and clearly explained.

In [ ]:
class SentimentDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None) -> None:
        self.encodings = encodings
        self.labels = labels

    def __len__(self) -> int:
        return len(self.encodings['input_ids'])

    def __getitem__(self, idx) -> dict[str, torch.Tensor]:
        # Create a dictionary with tokenized inputs for the given index
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}

        if self.labels is not None:
            item['labels'] = torch.tensor(self.labels[idx])

        return item

In [ ]:
def compute_accuracy(eval_pred) -> dict[str, float]:
    # Unpack predictions (logits) and true labels from eval_pred
    logits, labels = eval_pred.predictions, eval_pred.label_ids

    # Convert logits to predicted class indices by taking the argmax along the last dimension
    predictions = logits.argmax(axis=-1)

    # Calculate accuracy by comparing predicted classes with true labels
    accuracy = accuracy_score(labels, predictions)

    return {'accuracy': float(accuracy)}

In [ ]:
# Split the dataset into training and validation sets
train_texts, val_texts, train_labels, val_labels = model_selection.train_test_split(
    train['text'], train['label'], test_size=0.2, shuffle=True, random_state=42
)

# Load the tokenizer for BERT
tokenizer = transformers.BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenize the datasets with truncation and padding
train_encodings = tokenizer(
    list(train_texts), truncation=True, padding=True, max_length=128
)
val_encodings = tokenizer(
    list(val_texts), truncation=True, padding=True, max_length=128
)
test_encodings = tokenizer(
    list(test['text']), truncation=True, padding=True, max_length=128
)

# Wrap tokenized data in PyTorch datasets
train_dataset = SentimentDataset(train_encodings, list(train_labels))
val_dataset = SentimentDataset(val_encodings, list(val_labels))
test_dataset = SentimentDataset(test_encodings)

In [ ]:
# Load the pre-trained BERT model for sequence classification
model = transformers.BertForSequenceClassification.from_pretrained(
    'bert-base-uncased', num_labels=train['label'].nunique()
)

# Define training arguments
training_args = transformers.TrainingArguments(
    output_dir='./results',
    eval_strategy='epoch',
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=5,
    save_strategy='epoch',
    logging_dir='./logs',
    logging_steps=10,
)

# Initialize the Trainer
trainer = transformers.Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_accuracy,
)

# Train the model
trainer.train()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
d:\miniforge3\envs\ml\Lib\site-packages\accelerate\accelerator.py:449: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)

  0%|          | 0/1250 [00:00<?, ?it/s]

{'loss': 2.9976, 'grad_norm': 6.324663162231445, 'learning_rate': 4.96e-05, 'epoch': 0.04}
{'loss': 2.4472, 'grad_norm': 4.7166852951049805, 'learning_rate': 4.92e-05, 'epoch': 0.08}
{'loss': 2.2543, 'grad_norm': 4.426314353942871, 'learning_rate': 4.88e-05, 'epoch': 0.12}
{'loss': 2.0347, 'grad_norm': 5.824423789978027, 'learning_rate': 4.8400000000000004e-05, 'epoch': 0.16}
{'loss': 1.8751, 'grad_norm': 5.4824442863464355, 'learning_rate': 4.8e-05, 'epoch': 0.2}
{'loss': 1.717, 'grad_norm': 4.250117778778076, 'learning_rate': 4.76e-05, 'epoch': 0.24}
{'loss': 1.6962, 'grad_norm': 8.712447166442871, 'learning_rate': 4.72e-05, 'epoch': 0.28}
{'loss': 1.686, 'grad_norm': 5.414229869842529, 'learning_rate': 4.6800000000000006e-05, 'epoch': 0.32}
{'loss': 1.4258, 'grad_norm': 4.522858619689941, 'learning_rate': 4.64e-05, 'epoch': 0.36}
{'loss': 1.3507, 'grad_norm': 5.739327907562256, 'learning_rate': 4.600000000000001e-05, 'epoch': 0.4}
{'loss': 1.3273, 'grad_norm': 4.929150581359863, 'learning_rate': 4.5600000000000004e-05, 'epoch': 0.44}
{'loss': 1.3471, 'grad_norm': 6.493810653686523, 'learning_rate': 4.52e-05, 'epoch': 0.48}
{'loss': 1.1801, 'grad_norm': 6.577422142028809, 'learning_rate': 4.4840000000000004e-05, 'epoch': 0.52}
{'loss': 1.1754, 'grad_norm': 8.776657104492188, 'learning_rate': 4.444e-05, 'epoch': 0.56}
{'loss': 1.1409, 'grad_norm': 13.592077255249023, 'learning_rate': 4.4040000000000005e-05, 'epoch': 0.6}
{'loss': 1.0716, 'grad_norm': 8.824481010437012, 'learning_rate': 4.364e-05, 'epoch': 0.64}
{'loss': 1.1731, 'grad_norm': 20.216415405273438, 'learning_rate': 4.324e-05, 'epoch': 0.68}
{'loss': 1.0881, 'grad_norm': 6.390137672424316, 'learning_rate': 4.284e-05, 'epoch': 0.72}
{'loss': 1.0626, 'grad_norm': 9.652478218078613, 'learning_rate': 4.244e-05, 'epoch': 0.76}
{'loss': 1.0834, 'grad_norm': 11.12514591217041, 'learning_rate': 4.2040000000000004e-05, 'epoch': 0.8}
{'loss': 1.0057, 'grad_norm': 4.682662010192871, 'learning_rate': 4.164e-05, 'epoch': 0.84}
{'loss': 1.0315, 'grad_norm': 7.379148006439209, 'learning_rate': 4.124e-05, 'epoch': 0.88}
{'loss': 0.8972, 'grad_norm': 8.709019660949707, 'learning_rate': 4.084e-05, 'epoch': 0.92}
{'loss': 0.8437, 'grad_norm': 6.834367752075195, 'learning_rate': 4.044e-05, 'epoch': 0.96}
{'loss': 0.9782, 'grad_norm': 11.83719253540039, 'learning_rate': 4.004e-05, 'epoch': 1.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.9906200766563416, 'eval_accuracy': 0.741, 'eval_runtime': 3.2408, 'eval_samples_per_second': 617.123, 'eval_steps_per_second': 19.439, 'epoch': 1.0}
{'loss': 0.8553, 'grad_norm': 9.292866706848145, 'learning_rate': 3.964e-05, 'epoch': 1.04}
{'loss': 0.8295, 'grad_norm': 3.2123591899871826, 'learning_rate': 3.9240000000000004e-05, 'epoch': 1.08}
{'loss': 0.848, 'grad_norm': 5.4609503746032715, 'learning_rate': 3.884e-05, 'epoch': 1.12}
{'loss': 0.9649, 'grad_norm': 5.223743438720703, 'learning_rate': 3.8440000000000005e-05, 'epoch': 1.16}
{'loss': 0.8284, 'grad_norm': 4.045118808746338, 'learning_rate': 3.804e-05, 'epoch': 1.2}
{'loss': 0.8262, 'grad_norm': 5.452331066131592, 'learning_rate': 3.7640000000000006e-05, 'epoch': 1.24}
{'loss': 0.71, 'grad_norm': 3.912476062774658, 'learning_rate': 3.724e-05, 'epoch': 1.28}
{'loss': 0.7901, 'grad_norm': 11.989408493041992, 'learning_rate': 3.684e-05, 'epoch': 1.32}
{'loss': 0.8396, 'grad_norm': 5.7670745849609375, 'learning_rate': 3.6440000000000003e-05, 'epoch': 1.36}
{'loss': 0.701, 'grad_norm': 4.185752868652344, 'learning_rate': 3.604e-05, 'epoch': 1.4}
{'loss': 0.7706, 'grad_norm': 4.511607646942139, 'learning_rate': 3.5640000000000004e-05, 'epoch': 1.44}
{'loss': 0.8534, 'grad_norm': 2.9150564670562744, 'learning_rate': 3.524e-05, 'epoch': 1.48}
{'loss': 0.8316, 'grad_norm': 6.085832118988037, 'learning_rate': 3.484e-05, 'epoch': 1.52}
{'loss': 0.8371, 'grad_norm': 6.198502540588379, 'learning_rate': 3.444e-05, 'epoch': 1.56}
{'loss': 0.7336, 'grad_norm': 4.037014007568359, 'learning_rate': 3.408e-05, 'epoch': 1.6}
{'loss': 0.7734, 'grad_norm': 6.240649223327637, 'learning_rate': 3.368e-05, 'epoch': 1.64}
{'loss': 0.752, 'grad_norm': 8.150259017944336, 'learning_rate': 3.328e-05, 'epoch': 1.68}
{'loss': 0.7406, 'grad_norm': 5.21229362487793, 'learning_rate': 3.288e-05, 'epoch': 1.72}
{'loss': 0.7422, 'grad_norm': 7.643549919128418, 'learning_rate': 3.248e-05, 'epoch': 1.76}
{'loss': 0.79, 'grad_norm': 7.904196262359619, 'learning_rate': 3.208e-05, 'epoch': 1.8}
{'loss': 0.7769, 'grad_norm': 9.446266174316406, 'learning_rate': 3.168e-05, 'epoch': 1.84}
{'loss': 0.6601, 'grad_norm': 8.078688621520996, 'learning_rate': 3.1280000000000005e-05, 'epoch': 1.88}
{'loss': 0.754, 'grad_norm': 7.606196403503418, 'learning_rate': 3.088e-05, 'epoch': 1.92}
{'loss': 0.8705, 'grad_norm': 11.271876335144043, 'learning_rate': 3.0480000000000003e-05, 'epoch': 1.96}
{'loss': 0.6545, 'grad_norm': 3.207515239715576, 'learning_rate': 3.0080000000000003e-05, 'epoch': 2.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.8590283393859863, 'eval_accuracy': 0.763, 'eval_runtime': 3.2311, 'eval_samples_per_second': 618.991, 'eval_steps_per_second': 19.498, 'epoch': 2.0}
{'loss': 0.6546, 'grad_norm': 4.328280925750732, 'learning_rate': 2.9680000000000004e-05, 'epoch': 2.04}
{'loss': 0.5891, 'grad_norm': 5.307585716247559, 'learning_rate': 2.928e-05, 'epoch': 2.08}
{'loss': 0.5843, 'grad_norm': 4.577210426330566, 'learning_rate': 2.888e-05, 'epoch': 2.12}
{'loss': 0.5765, 'grad_norm': 9.775567054748535, 'learning_rate': 2.8480000000000002e-05, 'epoch': 2.16}
{'loss': 0.6475, 'grad_norm': 10.406607627868652, 'learning_rate': 2.8080000000000002e-05, 'epoch': 2.2}
{'loss': 0.5308, 'grad_norm': 6.331610202789307, 'learning_rate': 2.768e-05, 'epoch': 2.24}
{'loss': 0.6295, 'grad_norm': 5.049224853515625, 'learning_rate': 2.728e-05, 'epoch': 2.28}
{'loss': 0.6206, 'grad_norm': 5.963474750518799, 'learning_rate': 2.688e-05, 'epoch': 2.32}
{'loss': 0.6765, 'grad_norm': 7.778102397918701, 'learning_rate': 2.648e-05, 'epoch': 2.36}
{'loss': 0.5774, 'grad_norm': 10.225202560424805, 'learning_rate': 2.6079999999999998e-05, 'epoch': 2.4}
{'loss': 0.6301, 'grad_norm': 4.952739715576172, 'learning_rate': 2.5679999999999998e-05, 'epoch': 2.44}
{'loss': 0.6371, 'grad_norm': 4.192361354827881, 'learning_rate': 2.5280000000000005e-05, 'epoch': 2.48}
{'loss': 0.6249, 'grad_norm': 3.7490148544311523, 'learning_rate': 2.488e-05, 'epoch': 2.52}
{'loss': 0.4739, 'grad_norm': 4.159675121307373, 'learning_rate': 2.448e-05, 'epoch': 2.56}
{'loss': 0.5647, 'grad_norm': 6.594629764556885, 'learning_rate': 2.408e-05, 'epoch': 2.6}
{'loss': 0.6724, 'grad_norm': 4.118147850036621, 'learning_rate': 2.3680000000000004e-05, 'epoch': 2.64}
{'loss': 0.5656, 'grad_norm': 3.9190125465393066, 'learning_rate': 2.328e-05, 'epoch': 2.68}
{'loss': 0.5161, 'grad_norm': 4.2723164558410645, 'learning_rate': 2.288e-05, 'epoch': 2.72}
{'loss': 0.472, 'grad_norm': 5.464548110961914, 'learning_rate': 2.248e-05, 'epoch': 2.76}
{'loss': 0.6423, 'grad_norm': 7.186047554016113, 'learning_rate': 2.2080000000000002e-05, 'epoch': 2.8}
{'loss': 0.6837, 'grad_norm': 4.233503341674805, 'learning_rate': 2.168e-05, 'epoch': 2.84}
{'loss': 0.6076, 'grad_norm': 7.055222034454346, 'learning_rate': 2.128e-05, 'epoch': 2.88}
{'loss': 0.5539, 'grad_norm': 4.956688404083252, 'learning_rate': 2.0880000000000003e-05, 'epoch': 2.92}
{'loss': 0.7114, 'grad_norm': 9.123689651489258, 'learning_rate': 2.048e-05, 'epoch': 2.96}
{'loss': 0.4995, 'grad_norm': 5.151473522186279, 'learning_rate': 2.008e-05, 'epoch': 3.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.8416922688484192, 'eval_accuracy': 0.7655, 'eval_runtime': 3.2597, 'eval_samples_per_second': 613.56, 'eval_steps_per_second': 19.327, 'epoch': 3.0}
{'loss': 0.4552, 'grad_norm': 4.4009857177734375, 'learning_rate': 1.968e-05, 'epoch': 3.04}
{'loss': 0.4885, 'grad_norm': 5.062261581420898, 'learning_rate': 1.9280000000000002e-05, 'epoch': 3.08}
{'loss': 0.3812, 'grad_norm': 4.262712001800537, 'learning_rate': 1.888e-05, 'epoch': 3.12}
{'loss': 0.5301, 'grad_norm': 4.2871623039245605, 'learning_rate': 1.848e-05, 'epoch': 3.16}
{'loss': 0.3586, 'grad_norm': 2.1202077865600586, 'learning_rate': 1.808e-05, 'epoch': 3.2}
{'loss': 0.4631, 'grad_norm': 5.957062244415283, 'learning_rate': 1.7680000000000004e-05, 'epoch': 3.24}
{'loss': 0.5405, 'grad_norm': 4.925276756286621, 'learning_rate': 1.728e-05, 'epoch': 3.28}
{'loss': 0.4062, 'grad_norm': 2.342515230178833, 'learning_rate': 1.688e-05, 'epoch': 3.32}
{'loss': 0.4009, 'grad_norm': 2.273768186569214, 'learning_rate': 1.648e-05, 'epoch': 3.36}
{'loss': 0.3971, 'grad_norm': 5.731256008148193, 'learning_rate': 1.6080000000000002e-05, 'epoch': 3.4}
{'loss': 0.3739, 'grad_norm': 4.017038345336914, 'learning_rate': 1.568e-05, 'epoch': 3.44}
{'loss': 0.4763, 'grad_norm': 4.184810161590576, 'learning_rate': 1.528e-05, 'epoch': 3.48}
{'loss': 0.4887, 'grad_norm': 3.113738536834717, 'learning_rate': 1.488e-05, 'epoch': 3.52}
{'loss': 0.3756, 'grad_norm': 3.0523650646209717, 'learning_rate': 1.4480000000000002e-05, 'epoch': 3.56}
{'loss': 0.49, 'grad_norm': 2.3586251735687256, 'learning_rate': 1.408e-05, 'epoch': 3.6}
{'loss': 0.5242, 'grad_norm': 4.50405216217041, 'learning_rate': 1.3680000000000001e-05, 'epoch': 3.64}
{'loss': 0.4952, 'grad_norm': 5.791849613189697, 'learning_rate': 1.3280000000000002e-05, 'epoch': 3.68}
{'loss': 0.4363, 'grad_norm': 6.917680740356445, 'learning_rate': 1.288e-05, 'epoch': 3.72}
{'loss': 0.5153, 'grad_norm': 5.756560802459717, 'learning_rate': 1.248e-05, 'epoch': 3.76}
{'loss': 0.3611, 'grad_norm': 8.710748672485352, 'learning_rate': 1.2080000000000001e-05, 'epoch': 3.8}
{'loss': 0.3887, 'grad_norm': 3.243638277053833, 'learning_rate': 1.168e-05, 'epoch': 3.84}
{'loss': 0.5103, 'grad_norm': 5.930792331695557, 'learning_rate': 1.128e-05, 'epoch': 3.88}
{'loss': 0.5148, 'grad_norm': 12.92029094696045, 'learning_rate': 1.088e-05, 'epoch': 3.92}
{'loss': 0.4973, 'grad_norm': 3.243668794631958, 'learning_rate': 1.0480000000000001e-05, 'epoch': 3.96}
{'loss': 0.4623, 'grad_norm': 5.245966911315918, 'learning_rate': 1.008e-05, 'epoch': 4.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.8606656789779663, 'eval_accuracy': 0.7595, 'eval_runtime': 3.2486, 'eval_samples_per_second': 615.641, 'eval_steps_per_second': 19.393, 'epoch': 4.0}
{'loss': 0.4234, 'grad_norm': 3.2657532691955566, 'learning_rate': 9.68e-06, 'epoch': 4.04}
{'loss': 0.2932, 'grad_norm': 6.873795032501221, 'learning_rate': 9.28e-06, 'epoch': 4.08}
{'loss': 0.3823, 'grad_norm': 4.176461696624756, 'learning_rate': 8.880000000000001e-06, 'epoch': 4.12}
{'loss': 0.3613, 'grad_norm': 2.730264186859131, 'learning_rate': 8.48e-06, 'epoch': 4.16}
{'loss': 0.3263, 'grad_norm': 2.8528010845184326, 'learning_rate': 8.08e-06, 'epoch': 4.2}
{'loss': 0.3075, 'grad_norm': 1.8667662143707275, 'learning_rate': 7.68e-06, 'epoch': 4.24}
{'loss': 0.3263, 'grad_norm': 3.1212503910064697, 'learning_rate': 7.280000000000001e-06, 'epoch': 4.28}
{'loss': 0.4092, 'grad_norm': 5.206876277923584, 'learning_rate': 6.88e-06, 'epoch': 4.32}
{'loss': 0.2985, 'grad_norm': 4.010383605957031, 'learning_rate': 6.48e-06, 'epoch': 4.36}
{'loss': 0.3653, 'grad_norm': 8.469633102416992, 'learning_rate': 6.08e-06, 'epoch': 4.4}
{'loss': 0.3105, 'grad_norm': 2.198707342147827, 'learning_rate': 5.680000000000001e-06, 'epoch': 4.44}
{'loss': 0.3655, 'grad_norm': 3.849914312362671, 'learning_rate': 5.28e-06, 'epoch': 4.48}
{'loss': 0.3416, 'grad_norm': 3.939297914505005, 'learning_rate': 4.880000000000001e-06, 'epoch': 4.52}
{'loss': 0.3486, 'grad_norm': 6.101892471313477, 'learning_rate': 4.48e-06, 'epoch': 4.56}
{'loss': 0.3015, 'grad_norm': 3.9248831272125244, 'learning_rate': 4.080000000000001e-06, 'epoch': 4.6}
{'loss': 0.401, 'grad_norm': 3.1809558868408203, 'learning_rate': 3.68e-06, 'epoch': 4.64}
{'loss': 0.3747, 'grad_norm': 8.682636260986328, 'learning_rate': 3.2800000000000004e-06, 'epoch': 4.68}
{'loss': 0.3556, 'grad_norm': 4.359518527984619, 'learning_rate': 2.88e-06, 'epoch': 4.72}
{'loss': 0.326, 'grad_norm': 5.052278995513916, 'learning_rate': 2.48e-06, 'epoch': 4.76}
{'loss': 0.3197, 'grad_norm': 4.8171067237854, 'learning_rate': 2.08e-06, 'epoch': 4.8}
{'loss': 0.3254, 'grad_norm': 4.451800346374512, 'learning_rate': 1.68e-06, 'epoch': 4.84}
{'loss': 0.3265, 'grad_norm': 3.5225942134857178, 'learning_rate': 1.28e-06, 'epoch': 4.88}
{'loss': 0.2775, 'grad_norm': 3.8510630130767822, 'learning_rate': 8.8e-07, 'epoch': 4.92}
{'loss': 0.2967, 'grad_norm': 3.576967477798462, 'learning_rate': 4.8e-07, 'epoch': 4.96}
{'loss': 0.2975, 'grad_norm': 3.7965965270996094, 'learning_rate': 8e-08, 'epoch': 5.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.877459704875946, 'eval_accuracy': 0.7655, 'eval_runtime': 3.2466, 'eval_samples_per_second': 616.037, 'eval_steps_per_second': 19.405, 'epoch': 5.0}
{'train_runtime': 301.7256, 'train_samples_per_second': 132.571, 'train_steps_per_second': 4.143, 'train_loss': 0.7228744524002075, 'epoch': 5.0}

TrainOutput(global_step=1250, training_loss=0.7228744524002075, metrics={'train_runtime': 301.7256, 'train_samples_per_second': 132.571, 'train_steps_per_second': 4.143, 'total_flos': 1418664133440000.0, 'train_loss': 0.7228744524002075, 'epoch': 5.0})

In [ ]:
# Use the trained model to make predictions on the test dataset
predictions = trainer.predict(test_dataset)

# Extract the predicted class labels from the model's output logits
predicted_labels = torch.argmax(
    torch.tensor(predictions.predictions), axis=1  # pyright: ignore
)

# Add the predicted labels as a new column in the test DataFrame
test['label'] = predicted_labels.numpy()

# Save the results (id and label) to a CSV file for submission
test[['id', 'label']].to_csv('submission_bert.csv', index=False)

  0%|          | 0/469 [00:00<?, ?it/s]

In [ ]:
# Split the dataset into training and validation sets
train_texts, val_texts, train_labels, val_labels = model_selection.train_test_split(
    train['text'], train['label'], test_size=0.2, shuffle=True, random_state=42
)

# Load the tokenizer for DeBERTaV3
tokenizer = transformers.AutoTokenizer.from_pretrained('microsoft/deberta-v3-base')

# Tokenize the datasets with truncation and padding
train_encodings = tokenizer(
    list(train_texts), truncation=True, padding=True, max_length=128
)
val_encodings = tokenizer(
    list(val_texts), truncation=True, padding=True, max_length=128
)
test_encodings = tokenizer(
    list(test['text']), truncation=True, padding=True, max_length=128
)

# Wrap tokenized data in PyTorch datasets
train_dataset = SentimentDataset(train_encodings, list(train_labels))
val_dataset = SentimentDataset(val_encodings, list(val_labels))
test_dataset = SentimentDataset(test_encodings)

In [ ]:
# Load the pre-trained DeBERTaV3 model for sequence classification
model = transformers.AutoModelForSequenceClassification.from_pretrained(
    'microsoft/deberta-v3-base', num_labels=train['label'].nunique()
)

# Define training arguments
training_args = transformers.TrainingArguments(
    output_dir='./results',
    eval_strategy='epoch',
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=5,
    save_strategy='epoch',
    logging_dir='./logs',
    logging_steps=10,
)

# Initialize the Trainer
trainer = transformers.Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_accuracy,
)

# Train the model
trainer.train()

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
d:\miniforge3\envs\ml\Lib\site-packages\accelerate\accelerator.py:449: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)

  0%|          | 0/1250 [00:00<?, ?it/s]

{'loss': 3.1563, 'grad_norm': 4.6700758934021, 'learning_rate': 4.96e-05, 'epoch': 0.04}
{'loss': 2.543, 'grad_norm': 4.568312644958496, 'learning_rate': 4.92e-05, 'epoch': 0.08}
{'loss': 2.3188, 'grad_norm': 4.94827127456665, 'learning_rate': 4.88e-05, 'epoch': 0.12}
{'loss': 2.128, 'grad_norm': 6.527798652648926, 'learning_rate': 4.8400000000000004e-05, 'epoch': 0.16}
{'loss': 1.9475, 'grad_norm': 9.281331062316895, 'learning_rate': 4.8e-05, 'epoch': 0.2}
{'loss': 1.8138, 'grad_norm': 4.225669860839844, 'learning_rate': 4.76e-05, 'epoch': 0.24}
{'loss': 1.736, 'grad_norm': 11.278286933898926, 'learning_rate': 4.72e-05, 'epoch': 0.28}
{'loss': 1.7948, 'grad_norm': 8.859150886535645, 'learning_rate': 4.6800000000000006e-05, 'epoch': 0.32}
{'loss': 1.4834, 'grad_norm': 5.010193347930908, 'learning_rate': 4.64e-05, 'epoch': 0.36}
{'loss': 1.4954, 'grad_norm': 7.206892490386963, 'learning_rate': 4.600000000000001e-05, 'epoch': 0.4}
{'loss': 1.5395, 'grad_norm': 4.918926239013672, 'learning_rate': 4.5600000000000004e-05, 'epoch': 0.44}
{'loss': 1.6032, 'grad_norm': 4.790478706359863, 'learning_rate': 4.524000000000001e-05, 'epoch': 0.48}
{'loss': 1.4696, 'grad_norm': 16.03296661376953, 'learning_rate': 4.4840000000000004e-05, 'epoch': 0.52}
{'loss': 1.5171, 'grad_norm': 8.262350082397461, 'learning_rate': 4.444e-05, 'epoch': 0.56}
{'loss': 1.4612, 'grad_norm': 16.47724151611328, 'learning_rate': 4.4040000000000005e-05, 'epoch': 0.6}
{'loss': 1.4722, 'grad_norm': 4.7834954261779785, 'learning_rate': 4.364e-05, 'epoch': 0.64}
{'loss': 1.4936, 'grad_norm': 4.422555923461914, 'learning_rate': 4.324e-05, 'epoch': 0.68}
{'loss': 1.4343, 'grad_norm': 6.063866138458252, 'learning_rate': 4.284e-05, 'epoch': 0.72}
{'loss': 1.2418, 'grad_norm': 6.977006912231445, 'learning_rate': 4.244e-05, 'epoch': 0.76}
{'loss': 1.3256, 'grad_norm': 4.744787216186523, 'learning_rate': 4.2040000000000004e-05, 'epoch': 0.8}
{'loss': 1.2368, 'grad_norm': 6.535618305206299, 'learning_rate': 4.164e-05, 'epoch': 0.84}
{'loss': 1.3454, 'grad_norm': 6.95741605758667, 'learning_rate': 4.124e-05, 'epoch': 0.88}
{'loss': 1.2559, 'grad_norm': 8.310853958129883, 'learning_rate': 4.084e-05, 'epoch': 0.92}
{'loss': 1.1387, 'grad_norm': 5.148187160491943, 'learning_rate': 4.044e-05, 'epoch': 0.96}
{'loss': 1.2808, 'grad_norm': 17.522554397583008, 'learning_rate': 4.004e-05, 'epoch': 1.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 1.3096539974212646, 'eval_accuracy': 0.6055, 'eval_runtime': 4.6813, 'eval_samples_per_second': 427.229, 'eval_steps_per_second': 13.458, 'epoch': 1.0}
{'loss': 1.1955, 'grad_norm': 17.039634704589844, 'learning_rate': 3.964e-05, 'epoch': 1.04}
{'loss': 1.1416, 'grad_norm': 4.440891265869141, 'learning_rate': 3.9240000000000004e-05, 'epoch': 1.08}
{'loss': 1.0459, 'grad_norm': 6.883886814117432, 'learning_rate': 3.884e-05, 'epoch': 1.12}
{'loss': 1.1967, 'grad_norm': 9.190842628479004, 'learning_rate': 3.8440000000000005e-05, 'epoch': 1.16}
{'loss': 1.0243, 'grad_norm': 3.876006841659546, 'learning_rate': 3.804e-05, 'epoch': 1.2}
{'loss': 1.0118, 'grad_norm': 9.040027618408203, 'learning_rate': 3.7640000000000006e-05, 'epoch': 1.24}
{'loss': 0.9214, 'grad_norm': 4.258076190948486, 'learning_rate': 3.724e-05, 'epoch': 1.28}
{'loss': 0.9585, 'grad_norm': 3.3920304775238037, 'learning_rate': 3.684e-05, 'epoch': 1.32}
{'loss': 1.0575, 'grad_norm': 6.710408687591553, 'learning_rate': 3.6440000000000003e-05, 'epoch': 1.36}
{'loss': 0.8316, 'grad_norm': 3.7242913246154785, 'learning_rate': 3.604e-05, 'epoch': 1.4}
{'loss': 0.9854, 'grad_norm': 3.904165744781494, 'learning_rate': 3.5640000000000004e-05, 'epoch': 1.44}
{'loss': 0.9603, 'grad_norm': 6.22125768661499, 'learning_rate': 3.524e-05, 'epoch': 1.48}
{'loss': 0.9073, 'grad_norm': 4.352963924407959, 'learning_rate': 3.484e-05, 'epoch': 1.52}
{'loss': 0.9907, 'grad_norm': 9.987931251525879, 'learning_rate': 3.448e-05, 'epoch': 1.56}
{'loss': 0.9324, 'grad_norm': 3.447578191757202, 'learning_rate': 3.408e-05, 'epoch': 1.6}
{'loss': 0.9122, 'grad_norm': 3.988538980484009, 'learning_rate': 3.368e-05, 'epoch': 1.64}
{'loss': 0.8925, 'grad_norm': 7.47395658493042, 'learning_rate': 3.328e-05, 'epoch': 1.68}
{'loss': 0.8715, 'grad_norm': 5.604179859161377, 'learning_rate': 3.288e-05, 'epoch': 1.72}
{'loss': 0.9345, 'grad_norm': 7.704731464385986, 'learning_rate': 3.248e-05, 'epoch': 1.76}
{'loss': 0.903, 'grad_norm': 5.2303948402404785, 'learning_rate': 3.208e-05, 'epoch': 1.8}
{'loss': 0.9257, 'grad_norm': 3.193589925765991, 'learning_rate': 3.168e-05, 'epoch': 1.84}
{'loss': 0.803, 'grad_norm': 5.524363040924072, 'learning_rate': 3.1280000000000005e-05, 'epoch': 1.88}
{'loss': 0.8915, 'grad_norm': 4.778305530548096, 'learning_rate': 3.088e-05, 'epoch': 1.92}
{'loss': 0.9746, 'grad_norm': 6.591355800628662, 'learning_rate': 3.0480000000000003e-05, 'epoch': 1.96}
{'loss': 0.7603, 'grad_norm': 2.82403564453125, 'learning_rate': 3.0080000000000003e-05, 'epoch': 2.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.9512463212013245, 'eval_accuracy': 0.7485, 'eval_runtime': 4.5963, 'eval_samples_per_second': 435.132, 'eval_steps_per_second': 13.707, 'epoch': 2.0}
{'loss': 0.8449, 'grad_norm': 3.2123517990112305, 'learning_rate': 2.9680000000000004e-05, 'epoch': 2.04}
{'loss': 0.7717, 'grad_norm': 3.879169464111328, 'learning_rate': 2.928e-05, 'epoch': 2.08}
{'loss': 0.7733, 'grad_norm': 5.1093597412109375, 'learning_rate': 2.888e-05, 'epoch': 2.12}
{'loss': 0.7947, 'grad_norm': 4.608112812042236, 'learning_rate': 2.8480000000000002e-05, 'epoch': 2.16}
{'loss': 0.7869, 'grad_norm': 5.841500282287598, 'learning_rate': 2.8080000000000002e-05, 'epoch': 2.2}
{'loss': 0.7404, 'grad_norm': 12.811807632446289, 'learning_rate': 2.768e-05, 'epoch': 2.24}
{'loss': 0.8333, 'grad_norm': 4.682684898376465, 'learning_rate': 2.728e-05, 'epoch': 2.28}
{'loss': 0.8476, 'grad_norm': 8.84237003326416, 'learning_rate': 2.688e-05, 'epoch': 2.32}
{'loss': 0.8593, 'grad_norm': 6.199673652648926, 'learning_rate': 2.648e-05, 'epoch': 2.36}
{'loss': 0.7664, 'grad_norm': 1.65752112865448, 'learning_rate': 2.6079999999999998e-05, 'epoch': 2.4}
{'loss': 0.7837, 'grad_norm': 5.0549211502075195, 'learning_rate': 2.5679999999999998e-05, 'epoch': 2.44}
{'loss': 0.8533, 'grad_norm': 3.846116065979004, 'learning_rate': 2.5280000000000005e-05, 'epoch': 2.48}
{'loss': 0.8226, 'grad_norm': 4.292341709136963, 'learning_rate': 2.488e-05, 'epoch': 2.52}
{'loss': 0.678, 'grad_norm': 4.699778079986572, 'learning_rate': 2.448e-05, 'epoch': 2.56}
{'loss': 0.7674, 'grad_norm': 5.054069519042969, 'learning_rate': 2.408e-05, 'epoch': 2.6}
{'loss': 0.8463, 'grad_norm': 3.0488996505737305, 'learning_rate': 2.3680000000000004e-05, 'epoch': 2.64}
{'loss': 0.7204, 'grad_norm': 3.3520565032958984, 'learning_rate': 2.328e-05, 'epoch': 2.68}
{'loss': 0.7372, 'grad_norm': 2.6596899032592773, 'learning_rate': 2.288e-05, 'epoch': 2.72}
{'loss': 0.6676, 'grad_norm': 3.775437831878662, 'learning_rate': 2.248e-05, 'epoch': 2.76}
{'loss': 0.8366, 'grad_norm': 5.068906784057617, 'learning_rate': 2.2080000000000002e-05, 'epoch': 2.8}
{'loss': 0.7692, 'grad_norm': 3.8446671962738037, 'learning_rate': 2.168e-05, 'epoch': 2.84}
{'loss': 0.7976, 'grad_norm': 3.9012563228607178, 'learning_rate': 2.128e-05, 'epoch': 2.88}
{'loss': 0.7473, 'grad_norm': 2.6554923057556152, 'learning_rate': 2.0880000000000003e-05, 'epoch': 2.92}
{'loss': 0.8585, 'grad_norm': 4.196264266967773, 'learning_rate': 2.048e-05, 'epoch': 2.96}
{'loss': 0.665, 'grad_norm': 4.253872394561768, 'learning_rate': 2.008e-05, 'epoch': 3.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.9033052921295166, 'eval_accuracy': 0.7545, 'eval_runtime': 4.6522, 'eval_samples_per_second': 429.902, 'eval_steps_per_second': 13.542, 'epoch': 3.0}
{'loss': 0.7468, 'grad_norm': 4.5017805099487305, 'learning_rate': 1.968e-05, 'epoch': 3.04}
{'loss': 0.7064, 'grad_norm': 4.755809783935547, 'learning_rate': 1.9280000000000002e-05, 'epoch': 3.08}
{'loss': 0.6377, 'grad_norm': 4.4239935874938965, 'learning_rate': 1.888e-05, 'epoch': 3.12}
{'loss': 0.8535, 'grad_norm': 6.941289901733398, 'learning_rate': 1.848e-05, 'epoch': 3.16}
{'loss': 0.5228, 'grad_norm': 2.172137975692749, 'learning_rate': 1.808e-05, 'epoch': 3.2}
{'loss': 0.6558, 'grad_norm': 4.023258209228516, 'learning_rate': 1.7680000000000004e-05, 'epoch': 3.24}
{'loss': 0.7472, 'grad_norm': 4.946954250335693, 'learning_rate': 1.728e-05, 'epoch': 3.28}
{'loss': 0.6281, 'grad_norm': 4.706624984741211, 'learning_rate': 1.688e-05, 'epoch': 3.32}
{'loss': 0.6441, 'grad_norm': 3.0123724937438965, 'learning_rate': 1.648e-05, 'epoch': 3.36}
{'loss': 0.5972, 'grad_norm': 7.064026832580566, 'learning_rate': 1.6080000000000002e-05, 'epoch': 3.4}
{'loss': 0.5539, 'grad_norm': 2.856675386428833, 'learning_rate': 1.568e-05, 'epoch': 3.44}
{'loss': 0.7771, 'grad_norm': 4.076893329620361, 'learning_rate': 1.528e-05, 'epoch': 3.48}
{'loss': 0.8092, 'grad_norm': 3.992539882659912, 'learning_rate': 1.488e-05, 'epoch': 3.52}
{'loss': 0.5995, 'grad_norm': 3.5459303855895996, 'learning_rate': 1.4480000000000002e-05, 'epoch': 3.56}
{'loss': 0.6293, 'grad_norm': 2.3936140537261963, 'learning_rate': 1.408e-05, 'epoch': 3.6}
{'loss': 0.7931, 'grad_norm': 4.253058433532715, 'learning_rate': 1.3680000000000001e-05, 'epoch': 3.64}
{'loss': 0.6541, 'grad_norm': 5.210704326629639, 'learning_rate': 1.3280000000000002e-05, 'epoch': 3.68}
{'loss': 0.6452, 'grad_norm': 5.900237083435059, 'learning_rate': 1.288e-05, 'epoch': 3.72}
{'loss': 0.7616, 'grad_norm': 3.890125036239624, 'learning_rate': 1.248e-05, 'epoch': 3.76}
{'loss': 0.5122, 'grad_norm': 5.859831809997559, 'learning_rate': 1.2080000000000001e-05, 'epoch': 3.8}
{'loss': 0.6262, 'grad_norm': 3.892092227935791, 'learning_rate': 1.168e-05, 'epoch': 3.84}
{'loss': 0.7389, 'grad_norm': 4.017951488494873, 'learning_rate': 1.128e-05, 'epoch': 3.88}
{'loss': 0.7783, 'grad_norm': 4.744157791137695, 'learning_rate': 1.088e-05, 'epoch': 3.92}
{'loss': 0.6482, 'grad_norm': 2.1625730991363525, 'learning_rate': 1.0480000000000001e-05, 'epoch': 3.96}
{'loss': 0.6722, 'grad_norm': 5.898221969604492, 'learning_rate': 1.008e-05, 'epoch': 4.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.8551611304283142, 'eval_accuracy': 0.7635, 'eval_runtime': 4.6477, 'eval_samples_per_second': 430.322, 'eval_steps_per_second': 13.555, 'epoch': 4.0}
{'loss': 0.6937, 'grad_norm': 8.048962593078613, 'learning_rate': 9.68e-06, 'epoch': 4.04}
{'loss': 0.5431, 'grad_norm': 5.96552038192749, 'learning_rate': 9.28e-06, 'epoch': 4.08}
{'loss': 0.5305, 'grad_norm': 3.7225241661071777, 'learning_rate': 8.880000000000001e-06, 'epoch': 4.12}
{'loss': 0.6127, 'grad_norm': 3.8012313842773438, 'learning_rate': 8.48e-06, 'epoch': 4.16}
{'loss': 0.6017, 'grad_norm': 3.071937322616577, 'learning_rate': 8.08e-06, 'epoch': 4.2}
{'loss': 0.5676, 'grad_norm': 4.908409118652344, 'learning_rate': 7.68e-06, 'epoch': 4.24}
{'loss': 0.5614, 'grad_norm': 2.694415807723999, 'learning_rate': 7.280000000000001e-06, 'epoch': 4.28}
{'loss': 0.6363, 'grad_norm': 4.668781280517578, 'learning_rate': 6.88e-06, 'epoch': 4.32}
{'loss': 0.512, 'grad_norm': 3.0294878482818604, 'learning_rate': 6.48e-06, 'epoch': 4.36}
{'loss': 0.5986, 'grad_norm': 4.538196563720703, 'learning_rate': 6.08e-06, 'epoch': 4.4}
{'loss': 0.5328, 'grad_norm': 7.587865352630615, 'learning_rate': 5.680000000000001e-06, 'epoch': 4.44}
{'loss': 0.6166, 'grad_norm': 3.387340545654297, 'learning_rate': 5.28e-06, 'epoch': 4.48}
{'loss': 0.6552, 'grad_norm': 3.4590365886688232, 'learning_rate': 4.880000000000001e-06, 'epoch': 4.52}
{'loss': 0.6666, 'grad_norm': 4.889273643493652, 'learning_rate': 4.48e-06, 'epoch': 4.56}
{'loss': 0.6315, 'grad_norm': 5.178516387939453, 'learning_rate': 4.080000000000001e-06, 'epoch': 4.6}
{'loss': 0.6708, 'grad_norm': 4.3750433921813965, 'learning_rate': 3.68e-06, 'epoch': 4.64}
{'loss': 0.6227, 'grad_norm': 6.495596408843994, 'learning_rate': 3.2800000000000004e-06, 'epoch': 4.68}
{'loss': 0.6226, 'grad_norm': 3.3685975074768066, 'learning_rate': 2.88e-06, 'epoch': 4.72}
{'loss': 0.6208, 'grad_norm': 4.876758575439453, 'learning_rate': 2.48e-06, 'epoch': 4.76}
{'loss': 0.6395, 'grad_norm': 3.1470119953155518, 'learning_rate': 2.08e-06, 'epoch': 4.8}
{'loss': 0.5699, 'grad_norm': 6.5962443351745605, 'learning_rate': 1.68e-06, 'epoch': 4.84}
{'loss': 0.5203, 'grad_norm': 5.397777080535889, 'learning_rate': 1.28e-06, 'epoch': 4.88}
{'loss': 0.5106, 'grad_norm': 4.825087070465088, 'learning_rate': 8.8e-07, 'epoch': 4.92}
{'loss': 0.556, 'grad_norm': 3.8433873653411865, 'learning_rate': 4.8e-07, 'epoch': 4.96}
{'loss': 0.5217, 'grad_norm': 3.3997802734375, 'learning_rate': 8e-08, 'epoch': 5.0}

  0%|          | 0/63 [00:00<?, ?it/s]

{'eval_loss': 0.8544384241104126, 'eval_accuracy': 0.762, 'eval_runtime': 4.6585, 'eval_samples_per_second': 429.32, 'eval_steps_per_second': 13.524, 'epoch': 5.0}
{'train_runtime': 2327.5895, 'train_samples_per_second': 17.185, 'train_steps_per_second': 0.537, 'train_loss': 0.9326839370727539, 'epoch': 5.0}

TrainOutput(global_step=1250, training_loss=0.9326839370727539, metrics={'train_runtime': 2327.5895, 'train_samples_per_second': 17.185, 'train_steps_per_second': 0.537, 'total_flos': 1418689569600000.0, 'train_loss': 0.9326839370727539, 'epoch': 5.0})

In [ ]:
# Use the trained model to make predictions on the test dataset
predictions = trainer.predict(test_dataset)

# Extract the predicted class labels from the model's output logits
predicted_labels = torch.argmax(
    torch.tensor(predictions.predictions), axis=1  # pyright: ignore
)

# Add the predicted labels as a new column in the test DataFrame
test['label'] = predicted_labels.numpy()

# Save the results (id and label) to a CSV file for submission
test[['id', 'label']].to_csv('submission_deberta-v3.csv', index=False)

  0%|          | 0/469 [00:00<?, ?it/s]

<h3>2.2 Explanation in Words:</h3><p>
You need to answer the following questions in a markdown cell after this cell:

2.2.1 How much did you manage to improve performance on the test set? Did you beat "Zero Hero" in Kaggle? (Please include a screenshot of Kaggle Submission)

2.2.2 Please explain in detail how you achieved this and what you did specifically and why you tried this.

##### 2.2.1 How much did you manage to improve performance on the test set? Did you beat "Zero Hero" in Kaggle?

-   Yes, we managed to beat "Zero Hero" on Kaggle. Initially, using Bag-of-Words and SVM, we achieved an accuracy of 72.15%. After transitioning to BERT, the accuracy significantly improved to 76.36%. Finally, by using DeBERTa-v3, we achieved a slight improvement, reaching 77.19%. We used BERT because it processes the data bidirectionally, leading to a more nuanced understanding to word relationships.

<div style="text-align: center">
    <img
        alt="DeBERTaV3 Submission"
        src="https://github.com/Andy-Dihong-Luo/My-Image-Host/blob/master/Final%20Project/notebook_template/debertav3_submission_1733710363610.png?raw=true"
        width="90%"
    />
</div>

##### 2.2.2 Please explain in detail how you achieved this and what you did specifically and why you tried this.

1. Initial Challenges with Bag-of-Words and old models:

    - We started with a Bag-of-Words approach and SVM, achieving a test accuracy of 72.15%. However, the large number of features generated caused several challenges, including increased computational complexity, memory usage, and sparsity issues. We attempted to limit the number of features to improve SVM's performance, but observed no significant gains. This is likely because reducing the feature set removed important information, thereby limiting the model's ability to generalize effectively. We also tried to use Multidimensional Naive Bayes, but the training accuracy is low, about 60%. We think a possible reason is that Naive Bayes algorithm assumes the datasets are conditionally dependent. However, in reality, it may not.

2. Class Imbalance:

    - We noticed severe class imbalance in the dataset, where some labels were heavily underrepresented, causing the model to favor the majority class. We tried using `imbalanced-learn` to perform oversampling, but since one label had only 3 samples, oversampling (especially k-nearest neighbors-based methods) performed poorly.

3. Transition to BERT:

    - We transitioned to a pre-trained BERT model to address the limitations of Bag-of-Words and TF-IDF. Both Bag-of-Words and TF-IDF representations tend to produce sparse feature matrices, which can hinder model performance and generalization. BERT, on the other hand, uses a subword tokenization method and learns dense contextual embeddings, making it better suited for sentence-level sentiment analysis. Its ability to capture the meaning of words in context ensures that subtle relationships, such as negations or sentiment nuances, are effectively modeled. This transition significantly improved test accuracy to 76.36%.
    - We experimented with increasing the number of epochs but found that while the training loss decreased, validation accuracy plateaued, indicating a risk of overfitting. We decided to use 5 epochs as the optimal choice.

4. Using DeBERTa-v3:
    - Finally, we switched to DeBERTa-v3, a more advanced transformer model designed to better capture linguistic nuances and token relationships. DeBERTa improves upon BERT by using disentangled attention mechanisms, where word content and word position are encoded separately. This allows DeBERTa to capture sentence structure and context more effectively, which is crucial for nuanced tasks like sentiment analysis.
    - DeBERTa-v3 also leverages a more efficient pre-training objective, which further enhances its ability to generalize on downstream tasks. By transitioning to this model, we achieved a small but meaningful improvement, increasing test accuracy to 77.19%.
    - We opted for the `base` variant of DeBERTa-v3 rather than the larger model (`deberta-v3-large`) to balance performance and computational cost. The `large` model requires significantly more resources for both training and inference, which we deemed unnecessary given the relatively small performance gain it might bring in our use case.

<h2>Part 3: Kaggle Submission</h2><p>
You need to generate a prediction CSV using the following cell from your trained model and submit the direct output of your code to Kaggle. The results should be presented in two columns in csv format: the first column is the data id (0-14999) and the second column includes the predictions for the test set. The first column must be named id and the second column must be named label (otherwise your submission will fail). A sample predication file can be downloaded from Kaggle for each problem. 
We provide how to save a csv file if you are running Notebook on Kaggle.

In [ ]:
# id = range(15000)
# prediction = range(15000)
# submission = pd.DataFrame({'id': id, 'label': prediction})
# submission.to_csv('/kaggle/working/submission.csv', index=False)

In [ ]:
# You may use pandas to generate a dataframe with country, date and your predictions first
# and then use to_csv to generate a CSV file.

<h2>Part 4: Resources and Literature Used</h2><p>

Please cite the papers and open resources you used.

@misc{wolf2020huggingfacestransformersstateoftheartnatural,
title={HuggingFace's Transformers: State-of-the-art Natural Language Processing},
author={Thomas Wolf and Lysandre Debut and Victor Sanh and Julien Chaumond and Clement Delangue and Anthony Moi and Pierric Cistac and Tim Rault and Rémi Louf and Morgan Funtowicz and Joe Davison and Sam Shleifer and Patrick von Platen and Clara Ma and Yacine Jernite and Julien Plu and Canwen Xu and Teven Le Scao and Sylvain Gugger and Mariama Drame and Quentin Lhoest and Alexander M. Rush},
year={2020},
eprint={1910.03771},
archivePrefix={arXiv},
primaryClass={cs.CL},
url={https://arxiv.org/abs/1910.03771},
}

@article{DBLP:journals/corr/abs-1810-04805,
author = {Jacob Devlin and
Ming{-}Wei Chang and
Kenton Lee and
Kristina Toutanova},
title = {{BERT:} Pre-training of Deep Bidirectional Transformers for Language
Understanding},
journal = {CoRR},
volume = {abs/1810.04805},
year = {2018},
url = {http://arxiv.org/abs/1810.04805},
archivePrefix = {arXiv},
eprint = {1810.04805},
timestamp = {Tue, 30 Oct 2018 20:39:56 +0100},
biburl = {https://dblp.org/rec/journals/corr/abs-1810-04805.bib},
bibsource = {dblp computer science bibliography, https://dblp.org}
}

@misc{he2021debertav3,
title={DeBERTaV3: Improving DeBERTa using ELECTRA-Style Pre-Training with Gradient-Disentangled Embedding Sharing},
author={Pengcheng He and Jianfeng Gao and Weizhu Chen},
year={2021},
eprint={2111.09543},
archivePrefix={arXiv},
primaryClass={cs.CL}
}

@inproceedings{
he2021deberta,
title={DEBERTA: DECODING-ENHANCED BERT WITH DISENTANGLED ATTENTION},
author={Pengcheng He and Xiaodong Liu and Jianfeng Gao and Weizhu Chen},
booktitle={International Conference on Learning Representations},
year={2021},
url={https://openreview.net/forum?id=XPZIaotutsD}
}